name: MTK build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install doxygen cccc astyle
          sudo apt-get install libfltk1.3-dev

      - name: Build
        run: |
          make
